apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c6jz9x0ac-go
  janus-idp.io/tekton: c6jz9x0ac-go
  backstage.io/kubernetes-id: c6jz9x0ac-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c6jz9x0ac-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
